name: gldas-terrain-analysis
channels:
  - conda-forge
dependencies:
- geopandas==0.6.1
- Python==3.7.4 
- pip:
  - earthengine-api==0.1.221 
  - ee==0.2     
  - gdal==2.3.3
  - shapely
  - folium==0.11.0 
  - pyproj==2.6.1.post1 
  - requests==2.22.0   
  - requests-oauthlib==1.3.0    
  - pandas== 0.25.1 
  - matplotlib==3.1.3  
